### ISSUE TITLE
read_key and read_char do not work with yes tool in coreutils

### ISSUE THREAD

**Issue by hanabi1224** [console-rs/console#138]
I tried below sample program, the `read_key` and `read_char` do not seem to be able to read input from `yes` tool in `coreutils`, is that a bug?

Command: `yes | cargo run` or `yes n | cargo run`

```rust
use console::Term;

fn main() {
    let term = Term::stdout();
    term.write_line("Do you want to continue? [y|N]").unwrap();
    if let Ok(console::Key::Char(ch)) = term.read_key() {
        println!("reading key: {ch}");
    }
    if let Ok(ch) = term.read_char() {
        println!("reading char: {ch}");
    }
}
```

**Comment by mitsuhiko** [comment]
I am not sure to which degree it's "intentional" but that's more or less expected because these are not reading from stdin but the terminal. I'm quite sure that this is consistent with how other libraries are dealing with this as well. There is as far as I know no way to transparently read from stdin or the terminal. That's the same reason you can't pipe a password to a password prompt.
